--connect sys as sysdba
--show pdbs;
--alter pluggable database PAA_PDB open;

-- ALTER SESSION SET CONTAINER = имя_PDB;
-- GRANT ALL PRIVILEGES TO имя_пользователя;


alter session set "_ORACLE_SCRIPT" = true;

    --TASK №1

SELECT name, open_mode FROM v$pdbs;
SELECT pdb_name, pdb_id, status FROM SYS.dba_pdbs;

    -- TASK №2 --
SELECT * FROM v$instance;

    -- TASK №3 --
SELECT * FROM SYS.PRODUCT_COMPONENT_VERSION;

-- TASK №4 -- SQL DEVELOPER dbca
-- CREATE PLUGGABLE DATABASE PAA_PDB
-- ADMIN USER pdb_admin IDENTIFIED BY 12345
-- ROLES = (DBA)
-- FILE_NAME_CONVERT =('/u02/app/oracle/oradata/ORCL/pdbseed', '/u02/app/oracle/oradata/ORCL/PAA_PDB');

    -- TASK №5 -- SQL DEVELOPER dbca
SELECT name, open_mode FROM v$pdbs;
SELECT name FROM v$pdbs;

    -- TASK №6 (Это уже на PDB)
CREATE TABLESPACE TS_PAA
DATAFILE 'C:\LabWork\lw3\TS_PDB.dbf'
SIZE 7M
AUTOEXTEND ON NEXT 5M
MAXSIZE 30M;


CREATE TEMPORARY TABLESPACE TS_PAA_TEMP
TEMPFILE 'C:\LabWork\lw3\TS_PDB_TEMP.dbf'
SIZE 5M
AUTOEXTEND ON NEXT 3M
MAXSIZE 30M;

CREATE ROLE RL_PDB_PAA;
GRANT ALL PRIVILEGES TO RL_PDB_PAA;
GRANT CREATE SESSION TO RL_PDB_PAA;
COMMIT;


CREATE PROFILE PF_PDB_PAA LIMIT
PASSWORD_LIFE_TIME 180
SESSIONS_PER_USER 3
FAILED_LOGIN_ATTEMPTS 7
PASSWORD_LOCK_TIME 174
PASSWORD_REUSE_TIME 10
PASSWORD_GRACE_TIME DEFAULT
CONNECT_TIME 180
IDLE_TIME 30;

CREATE USER U1_PAA_PDB IDENTIFIED BY 12345
DEFAULT TABLESPACE TS_PAA
TEMPORARY TABLESPACE TS_PAA_TEMP
PROFILE PF_PDB_PAA
ACCOUNT UNLOCK;

GRANT RL_PDB_PAA TO U1_PAA_PDB;

DROP TABLESPACE TS_PAA INCLUDING CONTENTS AND DATAFILES;
DROP TABLESPACE TS_PAA_TEMP INCLUDING CONTENTS AND DATAFILES;
DROP USER U1_PAA_PDB;
DROP PROFILE PF_PDB_PAA;
DROP ROLE RL_PDB_PAA;

-- TASK №7 --
create  table  PAA_TABLE (
    id int,
    Name nvarchar2(20)
);

INSERT INTO PAA_TABLE (id, Name) VALUES (1, 'alex');
INSERT INTO PAA_TABLE (id, Name) VALUES (2, 'oleg');
INSERT INTO PAA_TABLE (id, Name) VALUES (3, 'vlad');
INSERT INTO PAA_TABLE (id, Name) VALUES (4, 'grad');

    -- TASK №8 --

SELECT TABLESPACE_NAME, STATUS, CONTENTS FROM USER_TABLESPACES;
SELECT TABLESPACE_NAME, FILE_NAME FROM DBA_DATA_FILES;
SELECT TABLESPACE_NAME, FILE_NAME FROM DBA_TEMP_FILES;
SELECT * FROM DBA_ROLES;
SELECT * FROM DBA_ROLE_PRIVS ORDER BY GRANTEE;
SELECT * FROM DBA_PROFILES ORDER BY PROFILE;
SELECT * FROM DBA_USERS ORDER BY USERNAME;
SELECT USERNAME, GRANTED_ROLE FROM DBA_USERS JOIN DBA_ROLE_PRIVS ON USERNAME = GRANTEE ORDER BY USERNAME;

    -- TASK 9 --
ALTER SESSION SET CONTAINER = CDB$ROOT;
CREATE USER C##PAA IDENTIFIED BY 12345 CONTAINER=ALL;
GRANT CREATE SESSION TO C##PAA CONTAINER=ALL;
ALTER USER C##PAA SET CONTAINER_DATA=PAA_PDB FOR CREATE SESSION;


CREATE USER C##PAA IDENTIFIED BY 12345
ACCOUNT UNLOCK;

GRANT CREATE SESSION TO C##PAA;
DROP USER  C##PAA;

-- TASK №11
SELECT * FROM v$session WHERE username IS NOT NULL;

-- TASK №12
SELECT *  FROM DBA_DATA_FILES;

-- TASK №13
ALTER PLUGGABLE DATABASE PAA_PDB CLOSE IMMEDIATE;
DROP PLUGGABLE DATABASE  PAA_PDB;
DROP USER C##PAA;