--TASK 1

--C:\app\User\product\21c\homes\OraDB21Home1\network\admin

--TASK 2

-- show parameter instance

--TASK 3

ALTER SESSION SET CONTAINER = XEPDB1;
SELECT SYS_CONTEXT ('USERENV', 'CON_NAME') FROM DUAL;

--sqlplus
SELECT * FROM V$PDBS;
SELECT * FROM V$TABLESPACE;
SELECT * FROM DBA_DATA_FILES;
SELECT * FROM ALL_USERS;
SELECT * FROM DBA_ROLE_PRIVS;

--TASK 5
connect U1_PAA_PDB/12345@lab6
--TASK 6

--connect PAA/12345@localhost:1521/XEPDB1

--TASK 7

SELECT * FROM PAA_T1;

--TASK 8

HELP
HELP INDEX
HELP TIMING


SET TIMING ON;

--TASK 9

-- Команда DESCRIBE в Oracle SQL*Plus используется для отображения структуры таблицы12.
-- Она выводит список столбцов таблицы вместе с их спецификациями1. Вот ее синтаксис1:
DESCRIBE PAA_T1

--TASK 10 ПОД SYSTEM

ALTER SESSION SET CONTAINER = XEPDB1;
SELECT SYS_CONTEXT ('USERENV', 'CON_NAME') FROM DUAL;
SELECT * FROM DBA_SEGMENTS WHERE OWNER = 'PAA';

--TASK 11

CREATE OR REPLACE VIEW SEGMENT_DETAILS AS
SELECT
    SEGMENT_NAME,
    SEGMENT_TYPE,
    COUNT(*) AS SEGMENT_COUNT,
    SUM(BYTES)/1024/1024 AS SIZE_IN_MB,
    SUM(EXTENTS) AS TOTAL_EXTENTS,
    SUM(BLOCKS) AS TOTAL_BLOCKS
FROM
    USER_SEGMENTS
GROUP BY
    SEGMENT_NAME, SEGMENT_TYPE;


SELECT * FROM SEGMENT_DETAILS;